### ISSUE TITLE
vaadin 7.6.1 version not working with dragdroplayouts 1.2 

### ISSUE THREAD

**Issue by santoshchimkode** [johndevs/dragdroplayouts#45] opened 2016-01-29 06:06 UTC
Hi
 i am using vaadin 7.4.3 with dragdroplayouts addon 1.1.3 version it is working fine.
but when i changed vaadin version to 7.6.1 and dragdroplayout 1.2 it is not working.

java.lang.ClassCastException: fi.jasoft.dragdroplayouts.client.ui.formlayout.DDFormLayoutState cannot be cast to com.vaadin.shared.ui.orderedlayout.FormLayoutState
    at com.vaadin.ui.FormLayout.getState(FormLayout.java:78)
    at com.vaadin.ui.FormLayout.getState(FormLayout.java:34)
    at fi.jasoft.dragdroplayouts.DDFormLayout.getState(DDFormLayout.java:244)
    at fi.jasoft.dragdroplayouts.DDFormLayout.getState(DDFormLayout.java:49)
    at com.vaadin.ui.AbstractOrderedLayout.setSpacing(AbstractOrderedLayout.java:291)
    at com.vaadin.ui.FormLayout.<init>(FormLayout.java:38)
    at fi.jasoft.dragdroplayouts.DDFormLayout.<init>(DDFormLayout.java:49)
   

please give solution

**Comment by johndevs** [comment] 2016-01-29 11:10
Can you verify that you are actually using dragdroplayouts 1.2 and don't have duplicate versions on your classpath? Also did you re-compile the widgetset after you updated?

Since 1.2 DDFormLayoutState extends FormLayoutState so you should not be able to get that excecption if you are using the right version.

**Comment by johndevs** [comment] 2016-02-05 09:26
Cannot reproduce this and closing this as this is  most likely an issue with the setup (multiple ddlayouts versions on the classpath).

**Closed by johndevs** 2016-02-05 09:26 UTC
